import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  route("api/events", "routes/api.events.ts"),
  route("api/assets", "routes/api.assets.ts"),
  route("api/quotes", "routes/api.quotes.ts"),
  route("api/qr", "routes/api.qr.ts"),
  route("api/convert", "routes/api.convert.ts"),
  route("api/pm/builder-sign", "routes/api.pm.builder-sign.ts"),
  route("api/pm/relayer-key", "routes/api.pm.relayer-key.ts"),
  route("api/pm/config", "routes/api.pm.config.ts"),
  route("api/pm/balance", "routes/api.pm.balance.ts"),
  route("api/pm/book", "routes/api.pm.book.ts"),
  route("api/pm/portfolio", "routes/api.pm.portfolio.ts"),
  route("api/pm/account", "routes/api.pm.account.ts"),
  route("api/pm/status", "routes/api.pm.status.ts"),
  route("api/pm/sponsor-tx", "routes/api.pm.sponsor-tx.ts"),
  route("api/rh/sponsor-send", "routes/api.rh.sponsor-send.ts"),
  route("api/rh/cash-in", "routes/api.rh.cash-in.ts"),
  route("api/rh/tokens", "routes/api.rh.tokens.ts"),
  route("api/relay/quote", "routes/api.relay.quote.ts"),
  route("api/relay/swap", "routes/api.relay.swap.ts"),
  route("api/relay/status", "routes/api.relay.status.ts"),
  route("api/relay/forward", "routes/api.relay.forward.ts"),
  route("api/track/trade", "routes/api.track.trade.ts"),
  route("api/track/nickname", "routes/api.track.nickname.ts"),
  route("api/referral", "routes/api.referral.ts"),
  route("api/referral/bind", "routes/api.referral.bind.ts"),
  route("api/referral/claim", "routes/api.referral.claim.ts"),
  route("api/challenge/leaderboard", "routes/api.challenge.leaderboard.ts"),
  route("api/venue/chat", "routes/api.venue.chat.ts"),
  route("api/token", "routes/api.token.ts"),
  route("api/vault", "routes/api.vault.ts"),
  route("api/leverage/orders", "routes/api.leverage.orders.ts"),
  route("api/leverage/refresh", "routes/api.leverage.refresh.ts"),
  route("api/hedgie", "routes/api.hedgie.ts"),
  route("api/agent", "routes/api.agent.ts"),
  route("api/agent/markets", "routes/api.agent.markets.ts"),
  route("api/agent/quote", "routes/api.agent.quote.ts"),
  route("api/agent/bets", "routes/api.agent.bets.ts"),
  route("api/agent/positions", "routes/api.agent.positions.ts"),
  route("llms.txt", "routes/llms.txt.ts"),
  route("ai", "routes/ai.tsx"),
  layout("routes/shell.tsx", [
    index("routes/home.tsx"),
    route("market/:id", "routes/market.$id.tsx"),
    route("profile", "routes/profile.tsx"),
    route("profile/referral", "routes/profile.referral.tsx"),
    route("earn", "routes/earn.tsx"),
    route("token", "routes/token.tsx"),
    route("roadmap", "routes/roadmap.tsx"),
    route("roademap", "routes/roademap.tsx"),
    route("terms", "routes/terms.tsx"),
    route("challenge", "routes/challenge.tsx"),
    route("rewards", "routes/rewards.tsx"),
    route("wall", "routes/wall.tsx"),
  ]),
] satisfies RouteConfig;
